platform :ios, '8.0'

target 'Velectric' do
    
    pod 'IQKeyboardManager', '~> 4.0.3'
    pod 'MJRefresh', '~> 3.0.0'
    pod 'SDWebImage', '~> 3.7.2'
    pod 'MJExtension', '~> 3.0.10'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Masonry', '~> 1.0.0'
    pod 'RegexKitLite', '~> 4.0'
    pod 'MBProgressHUD', '~> 0.9'
    pod 'TTTAttributedLabel', '~> 2.0.0'
    pod 'UMengAnalytics', '4.0.2'
    pod 'AliPay', '~> 2.1.2'
    pod 'YYModel', '~> 1.0.4'
    pod 'NinaPagerView'
    pod 'MMPopupView', '~> 1.7.2'
    
end
